///bassInit()

/*
 * BassWrapper 1.0
 * BASS 2.4.17.11
 */

var dll, rl, str, _;
dll = "BassWrapper.dll"
rl  = ty_real
str = ty_string
_   = dll_cdecl

global._bass_dll                    = dll
global._bass_init                   = external_define(dll, "bass_init", _, rl, 1, rl)
global._bass_free                   = external_define(dll, "bass_free", _, rl, 0)
global._bass_close                  = external_define(dll, "bass_close", _, rl, 0)
global._bass_getcpu                 = external_define(dll, "bass_getcpu", _, rl, 0)
global._bass_getversion             = external_define(dll, "bass_getversion", _, rl, 0)
global._bass_getwrapperversion      = external_define(dll, "bass_getwrapperversion", _, rl, 0)
global._bass_geterrorcode           = external_define(dll, "bass_geterrorcode", _, rl, 0)
global._bass_device_count           = external_define(dll, "bass_device_count", _, rl, 0)
global._bass_device_get             = external_define(dll, "bass_device_get", _, rl, 0)
global._bass_device_set             = external_define(dll, "bass_device_set", _, rl, 1, rl)
global._bass_device_getvolume       = external_define(dll, "bass_device_getvolume", _, rl, 0)
global._bass_device_setvolume       = external_define(dll, "bass_device_setvolume", _, rl, 1, rl)
global._bass_device_getname         = external_define(dll, "bass_device_getname", _, str, 1, rl)
global._bass_device_getdsversion    = external_define(dll, "bass_device_getdsversion", _, rl, 0)
global._bass_device_getlatency      = external_define(dll, "bass_device_getlatency", _, rl, 0)
global._bass_device_getspeakers     = external_define(dll, "bass_device_getspeakers", _, rl, 0)
global._bass_device_getfrequency    = external_define(dll, "bass_device_getfrequency", _, rl, 0)
global._bass_device_start           = external_define(dll, "bass_device_start", _, rl, 0)
global._bass_device_isstarted       = external_define(dll, "bass_device_isstarted", _, rl, 0)
global._bass_device_stop            = external_define(dll, "bass_device_stop", _, rl, 0)
global._bass_device_pause           = external_define(dll, "bass_device_pause", _, rl, 0)
global._bass_sample_load            = external_define(dll, "bass_sample_load", _, rl, 2, str, rl)
global._bass_sample_free            = external_define(dll, "bass_sample_free", _, rl, 1, rl)
global._bass_sample_play            = external_define(dll, "bass_sample_play", _, rl, 1, rl)
global._bass_sample_stop            = external_define(dll, "bass_sample_stop", _, rl, 1, rl)
global._bass_sample_getglobalvolume = external_define(dll, "bass_sample_getglobalvolume", _, rl, 0)
global._bass_sample_setglobalvolume = external_define(dll, "bass_sample_setglobalvolume", _, rl, 1, rl)
global._bass_sample_getvolume       = external_define(dll, "bass_sample_getvolume", _, rl, 1, rl)
global._bass_sample_setvolume       = external_define(dll, "bass_sample_setvolume", _, rl, 2, rl, rl)
global._bass_sample_getpitch        = external_define(dll, "bass_sample_getpitch", _, rl, 1, rl)
global._bass_sample_setpitch        = external_define(dll, "bass_sample_setpitch", _, rl, 2, rl, rl)
global._bass_sample_getpan          = external_define(dll, "bass_sample_getpan", _, rl, 1, rl)
global._bass_sample_setpan          = external_define(dll, "bass_sample_setpan", _, rl, 2, rl, rl)
global._bass_stream_load            = external_define(dll, "bass_stream_load", _, rl, 1, str)
global._bass_stream_free            = external_define(dll, "bass_stream_free", _, rl, 1, rl)
global._bass_stream_play            = external_define(dll, "bass_stream_play", _, rl, 1, rl)
global._bass_stream_stop            = external_define(dll, "bass_stream_stop", _, rl, 1, rl)
global._bass_stream_pause           = external_define(dll, "bass_stream_pause", _, rl, 1, rl)
global._bass_stream_resume          = external_define(dll, "bass_stream_resume", _, rl, 1, rl)
global._bass_stream_isplaying       = external_define(dll, "bass_stream_isplaying", _, rl, 1, rl)
global._bass_stream_ispaused        = external_define(dll, "bass_stream_ispaused", _, rl, 1, rl)
global._bass_stream_isstopped       = external_define(dll, "bass_stream_isstopped", _, rl, 1, rl)
global._bass_stream_getlength       = external_define(dll, "bass_stream_getlength", _, rl, 1, rl)
global._bass_stream_getposition     = external_define(dll, "bass_stream_getposition", _, rl, 1, rl)
global._bass_stream_setposition     = external_define(dll, "bass_stream_setposition", _, rl, 2, rl, rl)
global._bass_stream_getloop         = external_define(dll, "bass_stream_getloop", _, rl, 1, rl)
global._bass_stream_setloop         = external_define(dll, "bass_stream_setloop", _, rl, 2, rl, rl)
global._bass_stream_getloopstart    = external_define(dll, "bass_stream_getloopstart", _, rl, 1, rl)
global._bass_stream_setloopstart    = external_define(dll, "bass_stream_setloopstart", _, rl, 2, rl, rl)
global._bass_stream_getloopend      = external_define(dll, "bass_stream_getloopend", _, rl, 1, rl)
global._bass_stream_setloopend      = external_define(dll, "bass_stream_setloopend", _, rl, 2, rl, rl)
global._bass_stream_getglobalvolume = external_define(dll, "bass_stream_getglobalvolume", _, rl, 0)
global._bass_stream_setglobalvolume = external_define(dll, "bass_stream_setglobalvolume", _, rl, 1, rl)
global._bass_stream_getvolume       = external_define(dll, "bass_stream_getvolume", _, rl, 1, rl)
global._bass_stream_setvolume       = external_define(dll, "bass_stream_setvolume", _, rl, 2, rl, rl)
global._bass_stream_getpitch        = external_define(dll, "bass_stream_getpitch", _, rl, 1, rl)
global._bass_stream_setpitch        = external_define(dll, "bass_stream_setpitch", _, rl, 2, rl, rl)
global._bass_stream_getpan          = external_define(dll, "bass_stream_getpan", _, rl, 1, rl)
global._bass_stream_setpan          = external_define(dll, "bass_stream_setpan", _, rl, 2, rl, rl)
global._bass_stream_slidevolume     = external_define(dll, "bass_stream_slidevolume", _, rl, 3, rl, rl, rl)
global._bass_stream_slidepitch      = external_define(dll, "bass_stream_slidepitch", _, rl, 3, rl, rl, rl)
global._bass_stream_slidepan        = external_define(dll, "bass_stream_slidepan", _, rl, 3, rl, rl, rl)
global._bass_stream_isvolumesliding = external_define(dll, "bass_stream_isvolumesliding", rl, 1, rl)
global._bass_stream_ispitchsliding  = external_define(dll, "bass_stream_ispitchsliding", rl, 1, rl)
global._bass_stream_ispansliding    = external_define(dll, "bass_stream_ispansliding", rl, 1, rl)

external_call(global._bass_init, window_handle())
